# Generated by Django 4.0.3 on 2022-04-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_filesupload_delete_flupld'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilesUpload',
            new_name='Flupld',
        ),
    ]
